function generatePlan(){
  let age = document.getElementById('age').value;
  let weight = document.getElementById('weight').value;
  let goal = document.getElementById('goal').value;
  if(!age || !weight){ alert("Age & Weight fill pannu di!"); return; }
  document.getElementById('result').style.display='block';
  document.getElementById('planText').innerText = "Generating with Gemini AI...";
  setTimeout(()=>{
    let plan = `🔥 FitBuddy - Personalized Plan for You 🔥
Age: ${age}, Weight: ${weight}kg, Goal: ${goal}

✅ DIET PLAN:
Morning: Oats + Banana + Black Coffee
Afternoon: Brown Rice + Chicken/Fish + Veggies
Evening: Protein Shake + Nuts
Night: 2 Chapati + Curd

✅ WORKOUT PLAN (5 Days):
Day 1: Chest + Triceps - Pushups, Bench Press
Day 2: Back + Biceps - Pullups, Rows
Day 3: Legs + Core - Squats, Lunges
Day 4: Cardio + HIIT - 30 mins
Day 5: Full Body + Yoga

✅ AI TIPS (Generated by Gemini):
- Drink 3L water daily
- Sleep 7-8 hours
- Track calories using this app`;
    document.getElementById('planText').innerText = plan;
  },1500);
}
